// This file is auto-generated by running: dotnet run --project src/gapir -- --collect-reviewers  
// Do not edit manually - run the command above to regenerate
// Generated on: 2025-08-21 14:27:49
// Based on analysis of recent pull requests from AD-AggregatorService-Workloads repository

using System.Collections.Generic;

namespace gapir;

public static class ApiReviewersFallback
{
    /// <summary>
    /// Known API reviewers based on analysis of recent completed pull requests
    /// This is used as a fallback when the group membership API is not accessible
    /// Data collected from 50 recent PRs, showing reviewers who were marked as required or provided approval
    /// </summary>
    public static readonly HashSet<string> KnownApiReviewers = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        // Individual reviewers (email addresses) - sorted by frequency of being required reviewers
        "esownenf@microsoft.com",        // Required in 31 PRs (Ownership Enforcer)
        "chrispre@microsoft.com",        // Required in 6 PRs (Christof Sprenger)
        "dawambug@microsoft.com",        // Required in 6 PRs (David Wambugu) 
        "dbutoyi@microsoft.com",         // Required in 5 PRs (Derrick Butoyi)
        "shdo@microsoft.com",            // Required in 5 PRs (Shaowei Dong)
        "jiajyang@microsoft.com",        // Required in 5 PRs (Ashley Yang)
        "swapnilsapar@microsoft.com",    // Required in 4 PRs (Swapnil Sapar)
        "vchianese@microsoft.com",       // Required in 4 PRs (Vincenzo Chianese)
        "lekevi@microsoft.com",          // Required in 4 PRs (Kevin Lee - W365)
        "guoantang@microsoft.com",       // Required in 4 PRs (Guoan Tang)
        "darrmi@microsoft.com",          // Required in 3 PRs (Darrel Miller)
        "yadavgaurav@microsoft.com",     // Required in 3 PRs (Gaurav Yadav)
        "jaimb@microsoft.com",           // Required in 3 PRs (Jaiprakash Bankolli Mallikarjun)
        "jostetso@microsoft.com",        // Required in 3 PRs (Joshua Stetson)
        "davidra@microsoft.com",         // Required in 3 PRs (Dave Randall)
        "sakatuma@microsoft.com",        // Required in 2 PRs (Sandeep Katumalla)
        "mikep@microsoft.com",           // Required in 2 PRs (Michael Pizzo)
        "tcleveland@microsoft.com",      // Required in 2 PRs (Tyler Cleveland)
        "chetanpatel@microsoft.com",     // Required in 2 PRs (Chetan Patel - AAD)
        
        // Additional reviewers found in analysis
        "lieric@microsoft.com",          // Eric Lin
        "nijohn@microsoft.com",          // Nicholas Johnson
        "clhabins@microsoft.com",        // Clément Habinshuti
        "lipimehta@microsoft.com",       // Lipi Mehta
        "zhiweiyang@microsoft.com",      // Jensen Yang
        "frankgomulka@microsoft.com",    // Frank Gomulka
        "jshapoorjee@microsoft.com",     // Jamshed Shapoorjee
        
        // Legacy entries to maintain compatibility
        "duchau@microsoft.com",
        
        // Alternative formats that Azure DevOps might use (username without domain)
        "chrispre",
        "chetanpatel", 
        "duchau",
        "tcleveland",
        "darrmi",
        "vchianese",
        "mikep"
        
        // Note: Microsoft Graph API reviewers group found in 17 PRs but group membership needs to be resolved separately
        // Note: Other groups like "Graph Onboarding Internal", "Windows 365 Graph Team", "SCIM API reviewers" 
        // were also frequently required but need individual member resolution
    };
}
