// This file is auto-generated by scripts/update-api-reviewers.ps1
// Do not edit manually - it will be overwritten
// Generated on: 2024-01-15 10:30:00

using System.Collections.Generic;

namespace gapir
{
    public static class ApiReviewersFallback
    {
        /// <summary>
        /// Known API reviewers based on the Microsoft Graph API reviewers group
        /// This is used as a fallback when the group membership API is not accessible
        /// </summary>
        public static readonly HashSet<string> KnownApiReviewers = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            // Email addresses
            "chrispre@microsoft.com",
            "chetanpatel@microsoft.com", 
            "duchau@microsoft.com",
            "tcleveland@microsoft.com",
            
            // Alternative formats that Azure DevOps might use
            "chrispre",
            "chetanpatel", 
            "duchau",
            "tcleveland",
            
            // If you find the exact unique names from PRs, add them here
            // Format might be like: "Chris Pressey <chrispre@microsoft.com>"
        };
    }
}
