


### Pull Request Redirect (Supported - Base62 encoded)
GET http://g/pr/OwAc

### Pull Request Redirect (Supported - Decimal)
GET http://g/pr/12041652

### Pull Request Redirect - No ID (goes to base URL)
GET http://g/pr

### Favicon Request (Returns 404 but doesn't show error message)
GET http://g/favicon.ico

### Unsupported Path - Should show error message
GET http://g/google.com

### Root Path - Should show error message
GET http://g/

### Another Unsupported Path - Should show error message
GET http://g/search?q=test

